model: sell_in
sell_in:
  country: switzerland
#  column_historical_forecast: 'sales_forecast_volume_w-1'
  column_historical_forecast: 'sales_forecast_volume_w-4'
#  column_historical_forecast: 'forecast_volume_m-3'
  evaluation_start: 201801  #
  evaluation_end: 201852
  features:
    # Switch on/off features to train our XGBoost forecast model (& predict future volumes)
    cpg_trade_channel_indicator: True
    events: False
    open_orders: True
    open_orders_sum_to_date_to_predict: True
    plant_cpg_indicators: True
    promotion_uplift: True
    promotion_plan: False             # raw promotion features (1/2)
    promotion_cannibalization: False  # raw promotion features (2/2)
    rebates: False
    sales_customer_last_year_rolling: True
    sales_customer_sku_last_year_rolling: True
    sales_customer_sku_plant_last_year_rolling: True
    sales_force_activity_kpis: False
    seasonality: True
    sell_out_volumes: False
    sell_out_inventory: False
    shipped_orders: True
    shipped_orders_sum_to_date_to_predict: False
    sku_characteristics: True
    sku_segmentation: False           # Festival or promotion specific SKUs, or NPDs
    weather: True
  forecasting_horizons: [4]  # in weeks
  granularity:
    - lead_sku
    - calendar_yearweek
    - plant
    - customer_planning_group
  is_weekly_forecast: True
  main_data_version: '201901'  # Folder naming convention = week of extract (all files that must be updated)
  main_file_name: 'fc_acc_week.csv'
  train_model: True
  trained_model_file:  # '20190411_0846_forecast_model.pkl' # To open a specific model, ow load latest model
  train_start: 201601
  train_end: 201801
  use_light_regressor: False
  granularity_evaluator:
    level_1:
      - lead_sku
      - calendar_yearweek
      - plant
      - customer_planning_group
    level_2:
      - lead_sku
      - calendar_yearweek
      - customer_planning_group
    level_3:
      - lead_sku
      - calendar_yearweek
      - is_on_trade
    level_4:
      - lead_sku
      - calendar_yearweek
      - plant
    level_5:
      - lead_sku
      - calendar_yearweek
  xgboost_parameters:
    max_depth: 15
    n_estimators: 70
    learning_rate: 0.1
    n_jobs: 12
    verbosity: 2
  lightgbm_parameters:
    boosting_type: 'gbdt'
    max_depth': 15
    learning_rate: 0.1
    n_estimators: 70
    subsample_for_bin: 200000
    application': 'regression'
    n_jobs: 12
    silent: False
